- folderName: AI
  name: AI
  latestUpdated: '24:12:06:16:16'
- folderName: BaaS
  name: Baa S
  latestUpdated: '24:12:06:16:16'
- folderName: MPA
  name: MPA
  latestUpdated: '24:12:06:16:16'
- folderName: PWA
  name: PWA
  latestUpdated: '24:12:06:16:16'
- folderName: SSG
  name: SSG
  latestUpdated: '24:12:06:16:16'
- folderName: buildTools
  name: Build Tools
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:16:16'
  electiveGroup: Web Development
- folderName: cassandra
  name: Cassandra
  latestUpdated: '24:12:06:16:16'
- folderName: chat
  name: Chat
  latestUpdated: '24:12:06:16:16'
- folderName: clientTesting
  name: Client Testing
  latestUpdated: '24:12:06:16:16'
- folderName: cloudServices
  name: Cloud Services
  latestUpdated: '24:12:06:16:16'
- folderName: devops
  name: Devops
  latestUpdated: '24:12:06:16:16'
- folderName: docker
  name: Docker
  latestUpdated: '24:12:06:16:16'
- folderName: envVars
  name: Env Vars
  latestUpdated: '24:12:06:16:16'
- folderName: firebaseSecurity
  name: Firebase Security
  latestUpdated: '24:12:06:16:16'
- folderName: graphQl
  name: Graph Ql
  latestUpdated: '24:12:06:16:16'
- folderName: graphicsDesign
  name: Graphics Design
  latestUpdated: '24:12:06:16:16'
- folderName: i18
  name: I18
  latestUpdated: '24:12:06:16:16'
- folderName: jhipster
  name: Jhipster
  latestUpdated: '24:12:06:16:16'
- folderName: kafka
  name: Kafka
  latestUpdated: '24:12:06:16:16'
- folderName: layoutSpacing
  name: Layout Spacing
  latestUpdated: '24:12:06:16:16'
- folderName: lighthouse
  name: Lighthouse
  latestUpdated: '24:12:06:16:16'
- folderName: logging
  name: Logging
  latestUpdated: '24:12:06:16:16'
- folderName: markdown
  name: Markdown
  latestUpdated: '24:12:06:16:16'
- folderName: materialDesign
  name: Material Design
  latestUpdated: '24:12:06:16:16'
- folderName: mongo
  name: Mongo
  latestUpdated: '24:12:06:16:16'
- folderName: npm
  name: Npm
  latestUpdated: '24:12:06:16:16'
- folderName: react
  name: React
  latestUpdated: '24:12:06:16:16'
- folderName: reactive
  name: Reactive
  latestUpdated: '24:12:06:16:16'
- folderName: rust
  name: Rust
  latestUpdated: '24:12:06:16:16'
- folderName: serverless
  name: Serverless
  latestUpdated: '24:12:06:16:16'
- folderName: softskills
  name: Softskills
  latestUpdated: '24:12:06:16:16'
- folderName: swagger
  name: Swagger
  latestUpdated: '24:12:06:16:16'
- folderName: typescript
  name: Typescript
  latestUpdated: '24:12:06:16:16'
- folderName: uml
  name: Uml
  latestUpdated: '24:12:06:16:16'
- folderName: unitTesting
  name: Unit Testing
  latestUpdated: '24:12:06:16:16'
- folderName: video
  name: Video
  latestUpdated: '24:12:06:16:16'
- folderName: webAssembly
  name: Web Assembly
  latestUpdated: '24:12:06:16:16'
- folderName: webComponents
  name: Web Components
  latestUpdated: '24:12:06:16:16'
