- folderName: AI
  name: AI
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
  difficulty: Not Documented
  targetStack: Not Documented
  typicalTimeBudget: Not Documented
  other: see 241205_dev_notes
- folderName: BaaS
  name: Baa S
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: MPA
  name: MPA
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: PWA
  name: PWA
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: SSG
  name: SSG
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: buildTools
  name: Build Tools
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
  electiveGroup: Web Development
- folderName: cassandra
  name: Cassandra
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: chat
  name: Chat
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: clientTesting
  name: Client Testing
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: cloudServices
  name: Cloud Services
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: devops
  name: Devops
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: docker
  name: Docker
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: envVars
  name: Env Vars
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: firebaseSecurity
  name: Firebase Security
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: graphQl
  name: Graph Ql
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: graphicsDesign
  name: Graphics Design
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: i18
  name: I18
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: jhipster
  name: Jhipster
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: kafka
  name: Kafka
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: layoutSpacing
  name: Layout Spacing
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: lighthouse
  name: Lighthouse
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: logging
  name: Logging
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: markdown
  name: Markdown
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: materialDesign
  name: Material Design
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: mongo
  name: Mongo
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: npm
  name: Npm
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: react
  name: React
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: reactive
  name: Reactive
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: rust
  name: Rust
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: serverless
  name: Serverless
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: softskills
  name: Softskills
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: swagger
  name: Swagger
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: typescript
  name: Typescript
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: uml
  name: Uml
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: unitTesting
  name: Unit Testing
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: video
  name: Video
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: webAssembly
  name: Web Assembly
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
- folderName: webComponents
  name: Web Components
  points: 11
  historicalDemand: Not Documented
  latestUpdated: '24:12:06:14:53'
